/*
 * Token History API
 * # Introduction  Token History API allows users to search for information and transfer records on KLAY, FT (KIP-7, Labeled ERC-20), and NFT (KIP-17, Labeled ERC-721) tokens. You can use Token History API to check the records of a specific EOA transferring KLAY, retrieve NFT information, or other purposes.  For more details on Token History API, refer to our [tutorial](https://klaytn.com).  For any questions regarding this document or KAS, visit [the developer forum](https://forum.klaytn.com/).  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient', '../model/FtContract', '../model/Transaction'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'), require('./FtContract'), require('./Transaction'))
    } else {
        // Browser globals (root is window)
        if (!root.TokenHistoryApi) {
            root.TokenHistoryApi = {}
        }
        root.TokenHistoryApi.FtTransfer = factory(
            root.TokenHistoryApi.ApiClient,
            root.TokenHistoryApi.FtContract,
            root.TokenHistoryApi.Transaction
        )
    }
})(this, function(ApiClient, FtContract, Transaction) {
    /**
     * The FtTransfer model module.
     * @class FtTransfer
     * @version 1.0
     */

    /**
     * Constructs a new <code>FtTransfer</code>.
     * @alias FtTransfer
     * @class
     * @param contract {FtContract}
     * @param formattedValue {String} Converted value with the contract specific decimal
     * @param from {String} Sender EOA (20-byte)
     * @param to {String} Receiver EOA (20-byte)
     * @param transaction {Transaction}
     * @param transferType {String} Type of transaction detail
     * @param value {String} Number of tokens transferred (in hexadecimal)
     */
    const FtTransfer = function(contract, formattedValue, from, to, transaction, transferType, value) {
        this.contract = contract
        this.formattedValue = formattedValue
        this.from = from
        this.to = to
        this.transaction = transaction
        this.transferType = transferType
        this.value = value
    }

    /**
     * Constructs a <code>FtTransfer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {FtTransfer} obj Optional instance to populate.
     * @return {FtTransfer} The populated <code>FtTransfer</code> instance.
     * @memberof FtTransfer
     */
    FtTransfer.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new FtTransfer()
            if (data.hasOwnProperty('contract')) obj.contract = FtContract.constructFromObject(data.contract)
            if (data.hasOwnProperty('formattedValue')) obj.formattedValue = ApiClient.convertToType(data.formattedValue, 'String')
            if (data.hasOwnProperty('from')) obj.from = ApiClient.convertToType(data.from, 'String')
            if (data.hasOwnProperty('to')) obj.to = ApiClient.convertToType(data.to, 'String')
            if (data.hasOwnProperty('transaction')) obj.transaction = Transaction.constructFromObject(data.transaction)
            if (data.hasOwnProperty('transferType')) obj.transferType = ApiClient.convertToType(data.transferType, 'String')
            if (data.hasOwnProperty('value')) obj.value = ApiClient.convertToType(data.value, 'String')
        }
        return obj
    }

    /**
     * @type {FtContract}
     * @memberof FtTransfer
     */
    FtTransfer.prototype.contract = undefined

    /**
     * Converted value with the contract specific decimal
     * @type {String}
     * @memberof FtTransfer
     */
    FtTransfer.prototype.formattedValue = undefined

    /**
     * Sender EOA (20-byte)
     * @type {String}
     * @memberof FtTransfer
     */
    FtTransfer.prototype.from = undefined

    /**
     * Receiver EOA (20-byte)
     * @type {String}
     * @memberof FtTransfer
     */
    FtTransfer.prototype.to = undefined

    /**
     * @type {Transaction}
     * @memberof FtTransfer
     */
    FtTransfer.prototype.transaction = undefined

    /**
     * Type of transaction detail
     * @type {String}
     * @memberof FtTransfer
     */
    FtTransfer.prototype.transferType = undefined

    /**
     * Number of tokens transferred (in hexadecimal)
     * @type {String}
     * @memberof FtTransfer
     */
    FtTransfer.prototype.value = undefined

    return FtTransfer
})
