/*
 * Token History API
 * # Introduction  Token History API allows users to search for information and transfer records on KLAY, FT (KIP-7, Labeled ERC-20), and NFT (KIP-17, Labeled ERC-721) tokens. You can use Token History API to check the records of a specific EOA transferring KLAY, retrieve NFT information, or other purposes.  For more details on Token History API, refer to our [tutorial](https://klaytn.com).  For any questions regarding this document or KAS, visit [the developer forum](https://forum.klaytn.com/).
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient', '../model/MtContractDetail'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'), require('./MtContractDetail'))
    } else {
        // Browser globals (root is window)
        if (!root.TokenHistoryApi) {
            root.TokenHistoryApi = {}
        }
        root.TokenHistoryApi.PageableMtContractDetails = factory(root.TokenHistoryApi.ApiClient, root.TokenHistoryApi.MtContractDetail)
    }
})(this, function(ApiClient, MtContractDetail) {
    /**
     * The PageableMtContractDetails model module.
     * @class PageableMtContractDetails
     * @version 1.0
     */

    /**
     * Constructs a new <code>PageableMtContractDetails</code>.
     * @alias PageableMtContractDetails
     * @class
     * @param items {Array.<MtContractDetail>}
     * @param cursor {String} Offset for the next batch of items
     */
    const PageableMtContractDetails = function(items, cursor) {
        this.items = items
        this.cursor = cursor
    }

    /**
     * Constructs a <code>PageableMtContractDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {PageableMtContractDetails} obj Optional instance to populate.
     * @return {PageableMtContractDetails} The populated <code>PageableMtContractDetails</code> instance.
     * @memberof PageableMtContractDetails
     */
    PageableMtContractDetails.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new PageableMtContractDetails()
            if (data.hasOwnProperty('items')) obj.items = ApiClient.convertToType(data.items, [MtContractDetail])
            if (data.hasOwnProperty('cursor')) obj.cursor = ApiClient.convertToType(data.cursor, 'String')
        }
        return obj
    }

    /**
     * @type {Array.<MtContractDetail>}
     * @memberof PageableMtContractDetails
     */
    PageableMtContractDetails.prototype.items = undefined

    /**
     * Offset for the next batch of items
     * @type {String}
     * @memberof PageableMtContractDetails
     */
    PageableMtContractDetails.prototype.cursor = undefined

    return PageableMtContractDetails
})
