/**
 * KIP-7 API
 * # Introduction KIP-7 API is a RESTful API for managing KIP-7 contracts and tokens that follow the [KIP-7 Fungible Token Standard](https://kips.klaytn.com/KIPs/kip-7).   You can deploy contracts and send tokens using the default contract managing account (`deployer`) and an `alias`. And by using SDK like caver,  you can manage your contracts and tokens using [Wallet API](https://refs.klaytnapi.com/en/wallet/latest) for contracts created on the Klaytn Network.    # Error Codes  ## 400: Bad Request  | Code | Messages | | --- | --- | | 1130050 | incorrect request; spender | | 1130107 | incorrect bookmark | | 1134410 | invalid address; to</br>invalid address; owner</br>invalid address; address | | 1134411 | invalid amount; amount |  ## 404: Not Found  | Code | Messages | | --- | --- | | 1134504 | contract not found | | 1134506 | deployer not found |  ## 409: Conflict   | Code | Messages |   | --- | --- |   | 1134900 | duplicate alias 1134902 | contract already paused 1134903 | contract already unpaused |
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

const ApiClient = require('../../ApiClient')

/**
 * The Kip7DeployerResponse model module.
 * @class Kip7DeployerResponse
 * @version 1.0
 */
class Kip7DeployerResponse {
    /**
     * Constructs a new <code>Kip7DeployerResponse</code>.
     * @alias Kip7DeployerResponse
     * @class
     * @param address {String} Default Klaytn account address that manages the contracts
     * @param krn {String} KRN of the account
     */

    constructor(address, krn) {
        this.address = address
        this.krn = krn
    }

    /**
     * Constructs a <code>Kip7DeployerResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {Kip7DeployerResponse} obj Optional instance to populate.
     * @return {Kip7DeployerResponse} The populated <code>Kip7DeployerResponse</code> instance.
     * @memberof Kip7DeployerResponse
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Kip7DeployerResponse()

            if (data.hasOwnProperty('address')) {
                obj.address = ApiClient.convertToType(data.address, 'String')
            }
            if (data.hasOwnProperty('krn')) {
                obj.krn = ApiClient.convertToType(data.krn, 'String')
            }
        }
        return obj
    }
}

/**
 * Default Klaytn account address that manages the contracts
 * @type {String}
 * @memberof Kip7DeployerResponse
 */
Kip7DeployerResponse.prototype.address = undefined
/**
 * KRN of the account
 * @type {String}
 * @memberof Kip7DeployerResponse
 */
Kip7DeployerResponse.prototype.krn = undefined

module.exports = Kip7DeployerResponse
