/**
 * KIP-37 API
 * ## Introduction The KIP-37 API helps Blockchain app (BApp) developers to easily deploy smart contracts and send tokens of the [KIP-37 Multi Token Standard](https://kips.klaytn.com/KIPs/kip-37).  You can use the default contract managing account (`deployer`) and `alias`.    You can also manage the contracts and tokens created on the klaytn network using the caver SDK, using contract address and the [Wallet API](https://refs.klaytnapi.com/ko/wallet/latest) account.    ## Fee Payer Options  KAS KIP-37 supports four scenarios for paying transactin fees:      **1. Using only KAS Global FeePayer Account**   Sends all transactions using the KAS global FeePayer Account.       ``` {     \"options\": {       \"enableGlobalFeePayer\": true     }     } ```    <br />    **2. Using User FeePayer account**   Sends all transactions using the KAS User FeePayer Account.      ``` {   \"options\": {     \"enableGlobalFeePayer\": false,     \"userFeePayer\": {       \"krn\": \"krn:1001:wallet:20bab367-141b-439a-8b4c-ae8788b86316:feepayer-pool:default\",       \"address\": \"0xd6905b98E4Ba43a24E842d2b66c1410173791cab\"     }   } } ```    <br />  **3. Using both KAS Global FeePayer Account + User FeePayer Account**   Uses User FeePayer Account as default. When the balance runs out, KAS Global FeePayer Account will be used.     ``` {   \"options\": {     \"enableGlobalFeePayer\": true,     \"userFeePayer\": {       \"krn\": \"krn:1001:wallet:20bab367-141b-439a-8b4c-ae8788b86316:feepayer-pool:default\",       \"address\": \"0xd6905b98E4Ba43a24E842d2b66c1410173791cab\"     }   } } ```    <br />  **4. Not using FeePayer Account**   Sends a transaction via normal means where the sender pays the transaction fee.       ``` {   \"options\": {     \"enableGlobalFeePayer\": false   } } ```
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

const ApiClient = require('../../ApiClient')

/**
 * The CreateKip37TokenRequest model module.
 * @class CreateKip37TokenRequest
 * @version 1.0
 */
class CreateKip37TokenRequest {
    /**
     * Constructs a new <code>CreateKip37TokenRequest</code>.
     * @alias CreateKip37TokenRequest
     * @class
     * @param id {String} ID of the new token; cannot use an existing one
     * @param initialSupply {String} Initial supply (in hex.)
     * @param uri {String} Token URI
     */

    constructor(id, initialSupply, uri) {
        this.id = id
        this.initialSupply = initialSupply
        this.uri = uri
    }

    /**
     * Constructs a <code>CreateKip37TokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {CreateKip37TokenRequest} obj Optional instance to populate.
     * @return {CreateKip37TokenRequest} The populated <code>CreateKip37TokenRequest</code> instance.
     * @memberof CreateKip37TokenRequest
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateKip37TokenRequest()

            if (data.hasOwnProperty('sender')) {
                obj.sender = ApiClient.convertToType(data.sender, 'String')
            }
            if (data.hasOwnProperty('id')) {
                obj.id = ApiClient.convertToType(data.id, 'String')
            }
            if (data.hasOwnProperty('initialSupply')) {
                obj.initialSupply = ApiClient.convertToType(data.initialSupply, 'String')
            }
            if (data.hasOwnProperty('uri')) {
                obj.uri = ApiClient.convertToType(data.uri, 'String')
            }
        }
        return obj
    }
}

/**
 * The Klaytn account address to mint the token. The default value is the address that deployed the contract.
 * @type {String}
 * @memberof CreateKip37TokenRequest
 */
CreateKip37TokenRequest.prototype.sender = undefined
/**
 * ID of the new token; cannot use an existing one
 * @type {String}
 * @memberof CreateKip37TokenRequest
 */
CreateKip37TokenRequest.prototype.id = undefined
/**
 * Initial supply (in hex.)
 * @type {String}
 * @memberof CreateKip37TokenRequest
 */
CreateKip37TokenRequest.prototype.initialSupply = undefined
/**
 * Token URI
 * @type {String}
 * @memberof CreateKip37TokenRequest
 */
CreateKip37TokenRequest.prototype.uri = undefined

module.exports = CreateKip37TokenRequest
