/*
 * KIP-17 API
 *   # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1100050 | incorrect request 1100101 | data don't exist 1100251 | its value is out of range; size 1104401 | failed to get an account |   ## 404: Not Found   | Code | Messages |   | --- | --- |   | 1104404 | Token not found |   ## 409: Conflict   | Code | Messages |   | --- | --- |   | 1104400 | Duplicate alias - test |
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'))
    } else {
        // Browser globals (root is window)
        if (!root.Kip17Api) {
            root.Kip17Api = {}
        }
        root.Kip17Api.GetKip17TokenHistoryResponseItem = factory(root.Kip17Api.ApiClient)
    }
})(this, function(ApiClient) {
    /**
     * The GetKip17TokenHistoryResponseItem model module.
     * @class GetKip17TokenHistoryResponseItem
     * @version 1.0
     */

    /**
     * Constructs a new <code>GetKip17TokenHistoryResponseItem</code>.
     * @alias GetKip17TokenHistoryResponseItem
     * @class
     */
    const GetKip17TokenHistoryResponseItem = function() {}

    /**
     * Constructs a <code>GetKip17TokenHistoryResponseItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {GetKip17TokenHistoryResponseItem} obj Optional instance to populate.
     * @return {GetKip17TokenHistoryResponseItem} The populated <code>GetKip17TokenHistoryResponseItem</code> instance.
     * @memberof GetKip17TokenHistoryResponseItem
     */
    GetKip17TokenHistoryResponseItem.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new GetKip17TokenHistoryResponseItem()
            if (data.hasOwnProperty('from')) obj.from = ApiClient.convertToType(data.from, 'String')
            if (data.hasOwnProperty('timestamp')) obj.timestamp = ApiClient.convertToType(data.timestamp, 'Number')
            if (data.hasOwnProperty('to')) obj.to = ApiClient.convertToType(data.to, 'String')
        }
        return obj
    }

    /**
     * @type {String}
     * @memberof GetKip17TokenHistoryResponseItem
     */
    GetKip17TokenHistoryResponseItem.prototype.from = undefined

    /**
     * @type {Number}
     * @memberof GetKip17TokenHistoryResponseItem
     */
    GetKip17TokenHistoryResponseItem.prototype.timestamp = undefined

    /**
     * @type {String}
     * @memberof GetKip17TokenHistoryResponseItem
     */
    GetKip17TokenHistoryResponseItem.prototype.to = undefined

    return GetKip17TokenHistoryResponseItem
})
