/*
 * KIP-17 API
 *   # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1100050 | incorrect request 1100101 | data don't exist 1100251 | its value is out of range; size 1104401 | failed to get an account |   ## 404: Not Found   | Code | Messages |   | --- | --- |   | 1104404 | Token not found |   ## 409: Conflict   | Code | Messages |   | --- | --- |   | 1104400 | Duplicate alias - test |
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'))
    } else {
        // Browser globals (root is window)
        if (!root.Kip17Api) {
            root.Kip17Api = {}
        }
        root.Kip17Api.Kip17TokenListResponseItem = factory(root.Kip17Api.ApiClient)
    }
})(this, function(ApiClient) {
    /**
     * The Kip17TokenListResponseItem model module.
     * @class Kip17TokenListResponseItem
     * @version 1.0
     */

    /**
     * Constructs a new <code>Kip17TokenListResponseItem</code>.
     * @alias Kip17TokenListResponseItem
     * @class
     */
    const Kip17TokenListResponseItem = function() {}

    /**
     * Constructs a <code>Kip17TokenListResponseItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {Kip17TokenListResponseItem} obj Optional instance to populate.
     * @return {Kip17TokenListResponseItem} The populated <code>Kip17TokenListResponseItem</code> instance.
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new Kip17TokenListResponseItem()
            if (data.hasOwnProperty('createdAt')) obj.createdAt = ApiClient.convertToType(data.createdAt, 'Number')
            if (data.hasOwnProperty('owner')) obj.owner = ApiClient.convertToType(data.owner, 'String')
            if (data.hasOwnProperty('previousOwner')) obj.previousOwner = ApiClient.convertToType(data.previousOwner, 'String')
            if (data.hasOwnProperty('tokenId')) obj.tokenId = ApiClient.convertToType(data.tokenId, 'String')
            if (data.hasOwnProperty('tokenUri')) obj.tokenUri = ApiClient.convertToType(data.tokenUri, 'String')
            if (data.hasOwnProperty('transactionHash')) obj.transactionHash = ApiClient.convertToType(data.transactionHash, 'String')
            if (data.hasOwnProperty('updatedAt')) obj.updatedAt = ApiClient.convertToType(data.updatedAt, 'Number')
        }
        return obj
    }

    /**
     * @type {Number}
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.prototype.createdAt = undefined

    /**
     * @type {String}
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.prototype.owner = undefined

    /**
     * @type {String}
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.prototype.previousOwner = undefined

    /**
     * @type {String}
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.prototype.tokenId = undefined

    /**
     * @type {String}
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.prototype.tokenUri = undefined

    /**
     * @type {String}
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.prototype.transactionHash = undefined

    /**
     * @type {Number}
     * @memberof Kip17TokenListResponseItem
     */
    Kip17TokenListResponseItem.prototype.updatedAt = undefined

    return Kip17TokenListResponseItem
})
