/*
 * KIP-17 API Docs-EN
 *   # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1100050 | incorrect request 1100101 | data don't exist 1100251 | its value is out of range; size 1104401 | failed to get an account |   ## 404: Not Found   | Code | Messages |   | --- | --- |   | 1104404 | Token not found |   ## 409: Conflict   | Code | Messages |   | --- | --- |   | 1104400 | Duplicate alias - test |
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.18
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient', '../model/GetTokenResponse'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'), require('./GetTokenResponse'))
    } else {
        // Browser globals (root is window)
        if (!root.Kip17ApiDocsEn) {
            root.Kip17ApiDocsEn = {}
        }
        root.Kip17ApiDocsEn.ListTokensResponse = factory(root.Kip17ApiDocsEn.ApiClient, root.Kip17ApiDocsEn.GetTokenResponse)
    }
})(this, function(ApiClient, GetTokenResponse) {
    /**
     * The ListTokensResponse model module.
     * @class ListTokensResponse
     * @version 1.0
     */

    /**
     * Constructs a new <code>ListTokensResponse</code>.
     * @alias ListTokensResponse
     * @class
     * @param cursor {String} Offset for the next batch
     * @param items {Array.<GetTokenResponse>}
     */
    const ListTokensResponse = function(cursor, items) {
        this.cursor = cursor
        this.items = items
    }

    /**
     * Constructs a <code>ListTokensResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {ListTokensResponse} obj Optional instance to populate.
     * @return {ListTokensResponse} The populated <code>ListTokensResponse</code> instance.
     * @memberof ListTokensResponse
     */
    ListTokensResponse.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new ListTokensResponse()
            if (data.hasOwnProperty('cursor')) obj.cursor = ApiClient.convertToType(data.cursor, 'String')
            if (data.hasOwnProperty('items')) obj.items = ApiClient.convertToType(data.items, [GetTokenResponse])
        }
        return obj
    }

    /**
     * Offset for the next batch
     * @type {String}
     * @memberof ListTokensResponse
     */
    ListTokensResponse.prototype.cursor = undefined

    /**
     * @type {Array.<GetTokenResponse>}
     * @memberof ListTokensResponse
     */
    ListTokensResponse.prototype.items = undefined

    return ListTokensResponse
})
