/**
 * KIP-17 API
 *   # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1100050 | incorrect request 1100101 | data don't exist 1100251 | its value is out of range; size 1104401 | failed to get an account |   ## 404: Not Found   | Code | Messages |   | --- | --- |   | 1104404 | Token not found |   ## 409: Conflict   | Code | Messages |   | --- | --- |   | 1104400 | Duplicate alias - test |
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

const ApiClient = require('../../ApiClient')

/**
 * The TransferKip17TokenRequest model module.
 * @class TransferKip17TokenRequest
 * @version 1.0
 */
class TransferKip17TokenRequest {
    /**
     * Constructs a new <code>TransferKip17TokenRequest</code>.
     * @alias TransferKip17TokenRequest
     * @class
     * @param sender {String} Sender EOA address
     * @param owner {String} Current owner EOA address
     * @param to {String} Receiver EOA address
     */

    constructor(sender, owner, to) {
        this.sender = sender
        this.owner = owner
        this.to = to
    }

    /**
     * Constructs a <code>TransferKip17TokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {TransferKip17TokenRequest} obj Optional instance to populate.
     * @return {TransferKip17TokenRequest} The populated <code>TransferKip17TokenRequest</code> instance.
     * @memberof TransferKip17TokenRequest
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransferKip17TokenRequest()

            if (data.hasOwnProperty('sender')) {
                obj.sender = ApiClient.convertToType(data.sender, 'String')
            }
            if (data.hasOwnProperty('owner')) {
                obj.owner = ApiClient.convertToType(data.owner, 'String')
            }
            if (data.hasOwnProperty('to')) {
                obj.to = ApiClient.convertToType(data.to, 'String')
            }
        }
        return obj
    }
}

/**
 * Sender EOA address
 * @type {String}
 * @memberof TransferKip17TokenRequest
 */
TransferKip17TokenRequest.prototype.sender = undefined
/**
 * Current owner EOA address
 * @type {String}
 * @memberof TransferKip17TokenRequest
 */
TransferKip17TokenRequest.prototype.owner = undefined
/**
 * Receiver EOA address
 * @type {String}
 * @memberof TransferKip17TokenRequest
 */
TransferKip17TokenRequest.prototype.to = undefined

module.exports = TransferKip17TokenRequest
