/*
 * Anchor API
 * # Introduction This document discusses Klaytn API Service (KAS) Anchor API. Anchor API features functions for sending metadata to prove data reliability and ensuring the reliability of service chain data to the Klaytn main chain.     # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1071010 | data don't exist 1071615 | its value is out of range; size 1072100 | same payload ID or payload was already anchored 1072101 | all configured accounts have insufficient funds |   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'))
    } else {
        // Browser globals (root is window)
        if (!root.AnchorApi) {
            root.AnchorApi = {}
        }
        root.AnchorApi.AnchorBlockStatus = factory(root.AnchorApi.ApiClient)
    }
})(this, function(ApiClient) {
    /**
     * The AnchorBlockStatus model module.
     * @class AnchorBlockStatus
     * @version 1.0
     */

    /**
     * Constructs a new <code>AnchorBlockStatus</code>.
     * Anchoring state response
     * @alias AnchorBlockStatus
     * @class
     * @param status {String} Anchoring success/failure
     */
    const AnchorBlockStatus = function(status) {
        this.status = status
    }

    /**
     * Constructs a <code>AnchorBlockStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {AnchorBlockStatus} obj Optional instance to populate.
     * @return {AnchorBlockStatus} The populated <code>AnchorBlockStatus</code> instance.
     * @memberof AnchorBlockStatus
     */
    AnchorBlockStatus.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new AnchorBlockStatus()
            if (data.hasOwnProperty('status')) obj.status = ApiClient.convertToType(data.status, 'String')
        }
        return obj
    }

    /**
     * Anchoring success/failure
     * @type {String}
     * @memberof AnchorBlockStatus
     */
    AnchorBlockStatus.prototype.status = undefined

    return AnchorBlockStatus
})
