/**
 * Anchor API
 * # Introduction This document describes KAS (Klaytn API Service) Anchor API. Anchor API provides features sending metadata available to verify data reliability to ensure the reliability of service chain data to Klaytn main chain.  For more details on using the Anchor API, please refer to [Tutorial](https://docs.klaytnapi.com/tutorial/anchor-api).    # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1071010 | data don't exist 1071615 | its value is out of range; size 1072100 | same payload ID or payload was already anchored 1072101 | all configured accounts have insufficient funds |
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

const ApiClient = require('../../ApiClient')

/**
 * The ErrorResponse model module.
 * @class ErrorResponse
 * @version 1.0
 */
class ErrorResponse {
    /**
     * Constructs a new <code>ErrorResponse</code>.
     * @alias ErrorResponse
     * @class
     */

    constructor() {}

    /**
     * Constructs a <code>ErrorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {ErrorResponse} obj Optional instance to populate.
     * @return {ErrorResponse} The populated <code>ErrorResponse</code> instance.
     * @memberof ErrorResponse
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorResponse()

            if (data.hasOwnProperty('code')) {
                obj.code = ApiClient.convertToType(data.code, 'Number')
            }
            if (data.hasOwnProperty('message')) {
                obj.message = ApiClient.convertToType(data.message, 'String')
            }
            if (data.hasOwnProperty('requestId')) {
                obj.requestId = ApiClient.convertToType(data.requestId, 'String')
            }
        }
        return obj
    }
}

/**
 * @type {Number}
 * @memberof ErrorResponse
 */
ErrorResponse.prototype.code = undefined
/**
 * @type {String}
 * @memberof ErrorResponse
 */
ErrorResponse.prototype.message = undefined
/**
 * @type {String}
 * @memberof ErrorResponse
 */
ErrorResponse.prototype.requestId = undefined

module.exports = ErrorResponse
