/*
 * Anchor API
 * # Introduction This document describes KAS (Klaytn API Service) Anchor API. Anchor API provides features sending metadata available to verify data reliability to ensure the reliability of service chain data to Klaytn main chain.  For more details on using the Anchor API, please refer to [Tutorial](https://docs.klaytnapi.com/tutorial/anchor-api).    # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1071010 | data don't exist 1071615 | its value is out of range; size 1072100 | same payload ID or payload was already anchored 1072101 | all configured accounts have insufficient funds |
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.19
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'))
    } else {
        // Browser globals (root is window)
        if (!root.AnchorApi) {
            root.AnchorApi = {}
        }
        root.AnchorApi.OperatorSetting = factory(root.AnchorApi.ApiClient)
    }
})(this, function(ApiClient) {
    /**
     * The OperatorSetting model module.
     * @class OperatorSetting
     * @version 1.0
     */

    /**
     * Constructs a new <code>OperatorSetting</code>.
     * Operator pay information
     * @alias OperatorSetting
     * @class
     * @param useGlobalFeePayer {Boolean} Whether to use global fee delegation account
     * @param useOperator {Boolean} Whether to pay by operator
     */
    const OperatorSetting = function(useGlobalFeePayer, useOperator) {
        this.useGlobalFeePayer = useGlobalFeePayer
        this.useOperator = useOperator
    }

    /**
     * Constructs a <code>OperatorSetting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {OperatorSetting} obj Optional instance to populate.
     * @return {OperatorSetting} The populated <code>OperatorSetting</code> instance.
     * @memberof OperatorSetting
     */
    OperatorSetting.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new OperatorSetting()
            if (data.hasOwnProperty('feePayer')) obj.feePayer = ApiClient.convertToType(data.feePayer, 'String')
            if (data.hasOwnProperty('useGlobalFeePayer')) obj.useGlobalFeePayer = ApiClient.convertToType(data.useGlobalFeePayer, 'Boolean')
            if (data.hasOwnProperty('useOperator')) obj.useOperator = ApiClient.convertToType(data.useOperator, 'Boolean')
        }
        return obj
    }

    /**
     * @type {String}
     * @memberof OperatorSetting
     */
    OperatorSetting.prototype.feePayer = undefined

    /**
     * Whether to use global fee delegation account
     * @type {Boolean}
     * @memberof OperatorSetting
     */
    OperatorSetting.prototype.useGlobalFeePayer = undefined

    /**
     * Whether to pay by operator
     * @type {Boolean}
     * @memberof OperatorSetting
     */
    OperatorSetting.prototype.useOperator = undefined

    return OperatorSetting
})
