/*
 * Anchor API
 * # Introduction This document discusses Klaytn API Service (KAS) Anchor API. Anchor API features functions for sending metadata to prove data reliability and ensuring the reliability of service chain data to the Klaytn main chain.     # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1071010 | data don't exist 1071615 | its value is out of range; size 1072100 | same payload ID or payload was already anchored 1072101 | all configured accounts have insufficient funds |   # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.17
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient', '../model/Operator'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(require('../../ApiClient'), require('./Operator'))
    } else {
        // Browser globals (root is window)
        if (!root.AnchorApi) {
            root.AnchorApi = {}
        }
        root.AnchorApi.Operators = factory(root.AnchorApi.ApiClient, root.AnchorApi.Operator)
    }
})(this, function(ApiClient, Operator) {
    /**
     * The Operators model module.
     * @class Operators
     * @version 1.0
     */

    /**
     * Constructs a new <code>Operators</code>.
     * List of operators
     * @alias Operators
     * @class
     * @param cursor {String} Cursor information on last searched location
     */
    const Operators = function(cursor) {
        this.cursor = cursor
    }

    /**
     * Constructs a <code>Operators</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {Operators} obj Optional instance to populate.
     * @return {Operators} The populated <code>Operators</code> instance.
     * @memberof Operators
     */
    Operators.constructFromObject = function(data, obj) {
        if (data) {
            obj = obj || new Operators()
            if (data.hasOwnProperty('cursor')) obj.cursor = ApiClient.convertToType(data.cursor, 'String')
            if (data.hasOwnProperty('items')) obj.items = ApiClient.convertToType(data.items, [Operator])
        }
        return obj
    }

    /**
     * Cursor information on last searched location
     * @type {String}
     * @memberof Operators
     */
    Operators.prototype.cursor = undefined

    /**
     * @type {Array.<Operator>}
     * @memberof Operators
     */
    Operators.prototype.items = undefined

    return Operators
})
