/*
 * Anchor API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-anchor/v1/api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-anchor/v1/api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

;(function(factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define([
            './ApiClient',

            // Anchor
            './anchor/model/AnchorBlockRequest',
            './anchor/model/AnchorBlockStatus',
            './anchor/model/AnchorTransactionDetail',
            './anchor/model/AnchorTransaction',
            './anchor/model/AnchorTransactions',
            './anchor/model/Operator',
            './anchor/model/OperatorSetting',
            './anchor/model/Operators',
            './anchor/api/DataAnchoringTransactionApi',
            './anchor/api/OperatorApi',

            // TH
            './tokenHistory/model/FTSummary',
            './tokenHistory/model/FtContract',
            './tokenHistory/model/FtContractDetail',
            './tokenHistory/model/FtTransfer',
            './tokenHistory/model/KlayTransfer',
            './tokenHistory/model/Mt',
            './tokenHistory/model/MtContract',
            './tokenHistory/model/MtContractDetail',
            './tokenHistory/model/MtToken',
            './tokenHistory/model/MtTransfer',
            './tokenHistory/model/Nft',
            './tokenHistory/model/NftContract',
            './tokenHistory/model/NftContractDetail',
            './tokenHistory/model/NftOwnershipChange',
            './tokenHistory/model/NftTransfer',
            './tokenHistory/model/PageableAccountFT',
            './tokenHistory/model/PageableFtContractDetails',
            './tokenHistory/model/PageableMtContractDetails',
            './tokenHistory/model/PageableMtTokens',
            './tokenHistory/model/PageableMtTokensWithBalance',
            './tokenHistory/model/PageableMts',
            './tokenHistory/model/PageableNftContractDetails',
            './tokenHistory/model/PageableNftOwnershipChanges',
            './tokenHistory/model/PageableNfts',
            './tokenHistory/model/PageableTransfers',
            './tokenHistory/model/Transaction',
            './tokenHistory/model/TransferItem',
            './tokenHistory/model/Transfers',
            './tokenHistory/api/TokenApi',
            './tokenHistory/api/TokenContractApi',
            './tokenHistory/api/TokenHistoryApi',
            './tokenHistory/api/TokenOwnershipApi',

            // Wallet
            './wallet/model/Account',
            './wallet/model/AccountByPubkey',
            './wallet/model/AccountCountByAccountID',
            './wallet/model/AccountCountByKRN',
            './wallet/model/AccountRegistration',
            './wallet/model/AccountStatus',
            './wallet/model/AccountSummary',
            './wallet/model/AccountUpdateTransactionRequest',
            './wallet/model/Accounts',
            './wallet/model/AccountsByPubkey',
            './wallet/model/AnchorTransactionRequest',
            './wallet/model/CallArgument',
            './wallet/model/CancelTransactionRequest',
            './wallet/model/ContractCallData',
            './wallet/model/ContractCallRequest',
            './wallet/model/ContractCallResponse',
            './wallet/model/ContractDeployTransactionRequest',
            './wallet/model/ContractExecutionTransactionRequest',
            './wallet/model/EmptyUpdateKeyType',
            './wallet/model/ErrorResponse',
            './wallet/model/EventLog',
            './wallet/model/FDAccountUpdateTransactionRequest',
            './wallet/model/FDAnchorTransactionRequest',
            './wallet/model/FDCancelTransactionRequest',
            './wallet/model/FDContractDeployTransactionRequest',
            './wallet/model/FDContractExecutionTransactionRequest',
            './wallet/model/FDProcessRLPRequest',
            './wallet/model/FDTransactionResult',
            './wallet/model/FDUserAccountUpdateTransactionRequest',
            './wallet/model/FDUserAnchorTransactionRequest',
            './wallet/model/FDUserCancelTransactionRequest',
            './wallet/model/FDUserContractDeployTransactionRequest',
            './wallet/model/FDUserContractExecutionTransactionRequest',
            './wallet/model/FDUserProcessRLPRequest',
            './wallet/model/FDUserValueTransferTransactionRequest',
            './wallet/model/FDValueTransferTransactionRequest',
            './wallet/model/FeePayerSignaturesObj',
            './wallet/model/Key',
            './wallet/model/KeyCreationRequest',
            './wallet/model/KeyCreationResponse',
            './wallet/model/KeySignDataRequest',
            './wallet/model/KeySignDataResponse',
            './wallet/model/KeyStatus',
            './wallet/model/LegacyTransactionRequest',
            './wallet/model/MultisigAccount',
            './wallet/model/MultisigAccountUpdateRequest',
            './wallet/model/MultisigAddress',
            './wallet/model/MultisigKey',
            './wallet/model/MultisigTransactionStatus',
            './wallet/model/MultisigTransactions',
            './wallet/model/MultisigUpdateKey',
            './wallet/model/MultisigUpdateKeyType',
            './wallet/model/PendedTransaction',
            './wallet/model/ProcessRLPRequest',
            './wallet/model/PubkeyUpdateKeyType',
            './wallet/model/RoleBasedUpdateKeyType',
            './wallet/model/SignPendingTransactionBySigRequest',
            './wallet/model/Signature',
            './wallet/model/RegistrationStatusResponse',
            './wallet/model/TransactionReceipt',
            './wallet/model/TransactionResult',
            './wallet/model/TxData',
            './wallet/model/ValueTransferTransactionRequest',
            './wallet/api/AccountApi',
            './wallet/api/BasicTransactionApi',
            './wallet/api/FeeDelegatedTransactionPaidByKASApi',
            './wallet/api/FeeDelegatedTransactionPaidByUserApi',
            './wallet/api/FeepayerApi',
            './wallet/api/KeyApi',
            './wallet/api/MultisigTransactionManagementApi',
            './wallet/api/RegistrationApi',
            './wallet/api/StatisticsApi',

            // KIP17
            './kip17/model/ApproveAllKip17Request',
            './kip17/model/ApproveKip17TokenRequest',
            './kip17/model/BurnKip17TokenRequest',
            './kip17/model/DeployKip17ContractRequest',
            './kip17/model/GetKip17TokenHistoryResponse',
            './kip17/model/GetKip17TokenHistoryResponseItem',
            './kip17/model/GetKip17TokenResponse',
            './kip17/model/GetOwnerKip17TokensResponse',
            './kip17/model/GetOwnerKip17TokensResponseItem',
            './kip17/model/Kip17ContractInfoResponse',
            './kip17/model/Kip17ContractListResponse',
            './kip17/model/Kip17ContractListResponseItem',
            './kip17/model/Kip17TokenListResponse',
            './kip17/model/Kip17TransactionStatusResponse',
            './kip17/model/MintKip17TokenRequest',
            './kip17/model/TransferKip17TokenRequest',
            './kip17/api/KIP17Api',

            // KIP7
            './kip7/model/ApproveKip7TokenRequest',
            './kip7/model/BurnFromKip7TokenRequest',
            './kip7/model/BurnKip7TokenRequest',
            './kip7/model/DeployKip7ContractRequest',
            './kip7/model/Kip7ContractListResponse',
            './kip7/model/Kip7ContractListResponseItem',
            './kip7/model/Kip7ContractMetadataResponse',
            './kip7/model/Kip7DeployerResponse',
            './kip7/model/Kip7TokenBalanceResponse',
            './kip7/model/Kip7TransactionStatusResponse',
            './kip7/model/MintKip7TokenRequest',
            './kip7/model/TransferKip7TokenFromRequest',
            './kip7/model/TransferKip7TokenRequest',
            './kip7/api/KIP7Api',
            './kip7/api/KIP7DeployerApi',
        ], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(
            require('./ApiClient'),

            // Anchor
            require('./anchor/model/AnchorBlockRequest'),
            require('./anchor/model/AnchorBlockStatus'),
            require('./anchor/model/AnchorTransactionDetail'),
            require('./anchor/model/AnchorTransaction'),
            require('./anchor/model/AnchorTransactions'),
            require('./anchor/model/Operator'),
            require('./anchor/model/OperatorSetting'),
            require('./anchor/model/Operators'),
            require('./anchor/api/DataAnchoringTransactionApi'),
            require('./anchor/api/OperatorApi'),

            // TH
            require('./tokenHistory/model/FTSummary'),
            require('./tokenHistory/model/FtContract'),
            require('./tokenHistory/model/FtContractDetail'),
            require('./tokenHistory/model/FtTransfer'),
            require('./tokenHistory/model/KlayTransfer'),
            require('./tokenHistory/model/Mt'),
            require('./tokenHistory/model/MtContract'),
            require('./tokenHistory/model/MtContractDetail'),
            require('./tokenHistory/model/MtToken'),
            require('./tokenHistory/model/MtTransfer'),
            require('./tokenHistory/model/Nft'),
            require('./tokenHistory/model/NftContract'),
            require('./tokenHistory/model/NftContractDetail'),
            require('./tokenHistory/model/NftOwnershipChange'),
            require('./tokenHistory/model/NftTransfer'),
            require('./tokenHistory/model/PageableAccountFT'),
            require('./tokenHistory/model/PageableFtContractDetails'),
            require('./tokenHistory/model/PageableMtContractDetails'),
            require('./tokenHistory/model/PageableMtTokens'),
            require('./tokenHistory/model/PageableMtTokensWithBalance'),
            require('./tokenHistory/model/PageableMts'),
            require('./tokenHistory/model/PageableNftContractDetails'),
            require('./tokenHistory/model/PageableNftOwnershipChanges'),
            require('./tokenHistory/model/PageableNfts'),
            require('./tokenHistory/model/PageableTransfers'),
            require('./tokenHistory/model/Transaction'),
            require('./tokenHistory/model/TransferItem'),
            require('./tokenHistory/model/Transfers'),
            require('./tokenHistory/api/TokenApi'),
            require('./tokenHistory/api/TokenContractApi'),
            require('./tokenHistory/api/TokenHistoryApi'),
            require('./tokenHistory/api/TokenOwnershipApi'),

            // Wallet
            require('./wallet/model/Account'),
            require('./wallet/model/AccountByPubkey'),
            require('./wallet/model/AccountCountByAccountID'),
            require('./wallet/model/AccountCountByKRN'),
            require('./wallet/model/AccountRegistration'),
            require('./wallet/model/AccountStatus'),
            require('./wallet/model/AccountSummary'),
            require('./wallet/model/AccountUpdateTransactionRequest'),
            require('./wallet/model/Accounts'),
            require('./wallet/model/AccountsByPubkey'),
            require('./wallet/model/AnchorTransactionRequest'),
            require('./wallet/model/CallArgument'),
            require('./wallet/model/CancelTransactionRequest'),
            require('./wallet/model/ContractCallData'),
            require('./wallet/model/ContractCallRequest'),
            require('./wallet/model/ContractCallResponse'),
            require('./wallet/model/ContractDeployTransactionRequest'),
            require('./wallet/model/ContractExecutionTransactionRequest'),
            require('./wallet/model/EmptyUpdateKeyType'),
            require('./wallet/model/ErrorResponse'),
            require('./wallet/model/EventLog'),
            require('./wallet/model/FDAccountUpdateTransactionRequest'),
            require('./wallet/model/FDAnchorTransactionRequest'),
            require('./wallet/model/FDCancelTransactionRequest'),
            require('./wallet/model/FDContractDeployTransactionRequest'),
            require('./wallet/model/FDContractExecutionTransactionRequest'),
            require('./wallet/model/FDProcessRLPRequest'),
            require('./wallet/model/FDTransactionResult'),
            require('./wallet/model/FDUserAccountUpdateTransactionRequest'),
            require('./wallet/model/FDUserAnchorTransactionRequest'),
            require('./wallet/model/FDUserCancelTransactionRequest'),
            require('./wallet/model/FDUserContractDeployTransactionRequest'),
            require('./wallet/model/FDUserContractExecutionTransactionRequest'),
            require('./wallet/model/FDUserProcessRLPRequest'),
            require('./wallet/model/FDUserValueTransferTransactionRequest'),
            require('./wallet/model/FDValueTransferTransactionRequest'),
            require('./wallet/model/FeePayerSignaturesObj'),
            require('./wallet/model/Key'),
            require('./wallet/model/KeyCreationRequest'),
            require('./wallet/model/KeyCreationResponse'),
            require('./wallet/model/KeySignDataRequest'),
            require('./wallet/model/KeySignDataResponse'),
            require('./wallet/model/KeyStatus'),
            require('./wallet/model/LegacyTransactionRequest'),
            require('./wallet/model/MultisigAccount'),
            require('./wallet/model/MultisigAccountUpdateRequest'),
            require('./wallet/model/MultisigAddress'),
            require('./wallet/model/MultisigKey'),
            require('./wallet/model/MultisigTransactionStatus'),
            require('./wallet/model/MultisigTransactions'),
            require('./wallet/model/MultisigUpdateKey'),
            require('./wallet/model/MultisigUpdateKeyType'),
            require('./wallet/model/PendedTransaction'),
            require('./wallet/model/ProcessRLPRequest'),
            require('./wallet/model/PubkeyUpdateKeyType'),
            require('./wallet/model/RoleBasedUpdateKeyType'),
            require('./wallet/model/SignPendingTransactionBySigRequest'),
            require('./wallet/model/Signature'),
            require('./wallet/model/RegistrationStatusResponse'),
            require('./wallet/model/TransactionReceipt'),
            require('./wallet/model/TransactionResult'),
            require('./wallet/model/TxData'),
            require('./wallet/model/ValueTransferTransactionRequest'),
            require('./wallet/api/AccountApi'),
            require('./wallet/api/BasicTransactionApi'),
            require('./wallet/api/FeeDelegatedTransactionPaidByKASApi'),
            require('./wallet/api/FeeDelegatedTransactionPaidByUserApi'),
            require('./wallet/api/FeepayerApi'),
            require('./wallet/api/KeyApi'),
            require('./wallet/api/MultisigTransactionManagementApi'),
            require('./wallet/api/RegistrationApi'),
            require('./wallet/api/StatisticsApi'),

            // KIP17
            require('./kip17/model/ApproveAllKip17Request'),
            require('./kip17/model/ApproveKip17TokenRequest'),
            require('./kip17/model/BurnKip17TokenRequest'),
            require('./kip17/model/DeployKip17ContractRequest'),
            require('./kip17/model/GetKip17TokenHistoryResponse'),
            require('./kip17/model/GetKip17TokenHistoryResponseItem'),
            require('./kip17/model/GetKip17TokenResponse'),
            require('./kip17/model/GetOwnerKip17TokensResponse'),
            require('./kip17/model/GetOwnerKip17TokensResponseItem'),
            require('./kip17/model/Kip17ContractInfoResponse'),
            require('./kip17/model/Kip17ContractListResponse'),
            require('./kip17/model/Kip17ContractListResponseItem'),
            require('./kip17/model/Kip17TokenListResponse'),
            require('./kip17/model/Kip17TransactionStatusResponse'),
            require('./kip17/model/MintKip17TokenRequest'),
            require('./kip17/model/TransferKip17TokenRequest'),
            require('./kip17/api/KIP17Api'),

            // KIP7
            require('./kip7/model/ApproveKip7TokenRequest'),
            require('./kip7/model/BurnFromKip7TokenRequest'),
            require('./kip7/model/BurnKip7TokenRequest'),
            require('./kip7/model/DeployKip7ContractRequest'),
            require('./kip7/model/Kip7ContractListResponse'),
            require('./kip7/model/Kip7ContractListResponseItem'),
            require('./kip7/model/Kip7ContractMetadataResponse'),
            require('./kip7/model/Kip7DeployerResponse'),
            require('./kip7/model/Kip7TokenBalanceResponse'),
            require('./kip7/model/Kip7TransactionStatusResponse'),
            require('./kip7/model/MintKip7TokenRequest'),
            require('./kip7/model/TransferKip7TokenFromRequest'),
            require('./kip7/model/TransferKip7TokenRequest'),
            require('./kip7/api/KIP7Api'),
            require('./kip7/api/KIP7DeployerApi')
        )
    }
})(function(
    ApiClient,

    // Anchor
    AnchorBlockRequest,
    AnchorBlockStatus,
    AnchorTransactionDetail,
    AnchorTransaction,
    AnchorTransactions,
    Operator,
    OperatorSetting,
    Operators,
    DataAnchoringTransactionApi,
    OperatorApi,

    // TH
    FTSummary,
    FtContract,
    FtContractDetail,
    FtTransfer,
    KlayTransfer,
    Mt,
    MtContract,
    MtContractDetail,
    MtToken,
    MtTransfer,
    Nft,
    NftContract,
    NftContractDetail,
    NftOwnershipChange,
    NftTransfer,
    PageableAccountFT,
    PageableFtContractDetails,
    PageableMtContractDetails,
    PageableMtTokens,
    PageableMtTokensWithBalance,
    PageableMts,
    PageableNftContractDetails,
    PageableNftOwnershipChanges,
    PageableNfts,
    PageableTransfers,
    Transaction,
    TransferItem,
    Transfers,
    TokenApi,
    TokenContractApi,
    TokenHistoryApi,
    TokenOwnershipApi,

    // Wallet
    Account,
    AccountByPubkey,
    AccountCountByAccountID,
    AccountCountByKRN,
    AccountRegistration,
    AccountStatus,
    AccountSummary,
    AccountUpdateTransactionRequest,
    Accounts,
    AccountsByPubkey,
    AnchorTransactionRequest,
    CallArgument,
    CancelTransactionRequest,
    ContractCallData,
    ContractCallRequest,
    ContractCallResponse,
    ContractDeployTransactionRequest,
    ContractExecutionTransactionRequest,
    EmptyUpdateKeyType,
    ErrorResponse,
    EventLog,
    FDAccountUpdateTransactionRequest,
    FDAnchorTransactionRequest,
    FDCancelTransactionRequest,
    FDContractDeployTransactionRequest,
    FDContractExecutionTransactionRequest,
    FDProcessRLPRequest,
    FDTransactionResult,
    FDUserAccountUpdateTransactionRequest,
    FDUserAnchorTransactionRequest,
    FDUserCancelTransactionRequest,
    FDUserContractDeployTransactionRequest,
    FDUserContractExecutionTransactionRequest,
    FDUserProcessRLPRequest,
    FDUserValueTransferTransactionRequest,
    FDValueTransferTransactionRequest,
    FeePayerSignaturesObj,
    Key,
    KeyCreationRequest,
    KeyCreationResponse,
    KeySignDataRequest,
    KeySignDataResponse,
    KeyStatus,
    LegacyTransactionRequest,
    MultisigAccount,
    MultisigAccountUpdateRequest,
    MultisigAddress,
    MultisigKey,
    MultisigTransactionStatus,
    MultisigTransactions,
    MultisigUpdateKey,
    MultisigUpdateKeyType,
    PendedTransaction,
    ProcessRLPRequest,
    PubkeyUpdateKeyType,
    RoleBasedUpdateKeyType,
    SignPendingTransactionBySigRequest,
    Signature,
    RegistrationStatusResponse,
    TransactionReceipt,
    TransactionResult,
    TxData,
    ValueTransferTransactionRequest,
    AccountApi,
    BasicTransactionApi,
    FeeDelegatedTransactionPaidByKASApi,
    FeeDelegatedTransactionPaidByUserApi,
    FeepayerApi,
    KeyApi,
    MultisigTransactionManagementApi,
    RegistrationApi,
    StatisticsApi,
    ApproveAllKip17Request,
    ApproveKip17TokenRequest,
    BurnKip17TokenRequest,
    DeployKip17ContractRequest,
    GetKip17TokenHistoryResponse,
    GetKip17TokenHistoryResponseItem,
    GetKip17TokenResponse,
    GetOwnerKip17TokensResponse,
    GetOwnerKip17TokensResponseItem,
    Kip17ContractInfoResponse,
    Kip17ContractListResponse,
    Kip17ContractListResponseItem,
    Kip17TokenListResponse,
    Kip17TransactionStatusResponse,
    MintKip17TokenRequest,
    TransferKip17TokenRequest,
    KIP17Api,

    // KIP7
    ApproveKip7TokenRequest,
    BurnFromKip7TokenRequest,
    BurnKip7TokenRequest,
    DeployKip7ContractRequest,
    Kip7ContractListResponse,
    Kip7ContractListResponseItem,
    Kip7ContractMetadataResponse,
    Kip7DeployerResponse,
    Kip7TokenBalanceResponse,
    Kip7TransactionStatusResponse,
    MintKip7TokenRequest,
    TransferKip7TokenFromRequest,
    TransferKip7TokenRequest,
    KIP7Api,
    KIP7DeployerApi
) {
    /**
     * @module RestClient
     * @version 1.0
     */
    const exports = {
        /**
         * The ApiClient constructor.
         * @property {ApiClient}
         */
        ApiClient: ApiClient,

        // Anchor
        /**
         * The AnchorBlockRequest model constructor.
         * @property {AnchorBlockRequest}
         */
        AnchorBlockRequest: AnchorBlockRequest,
        /**
         * The AnchorBlockStatus model constructor.
         * @property {AnchorBlockStatus}
         */
        AnchorBlockStatus: AnchorBlockStatus,
        /**
         * The AnchorTransactionDetail model constructor.
         * @property {AnchorTransactionDetail}
         */
        AnchorTransactionDetail: AnchorTransactionDetail,
        /**
         * The AnchorTransaction model constructor.
         * @property {AnchorTransaction}
         */
        AnchorTransaction: AnchorTransaction,
        /**
         * The AnchorTransactions model constructor.
         * @property {AnchorTransactions}
         */
        AnchorTransactions: AnchorTransactions,
        /**
         * The Operator model constructor.
         * @property {Operator}
         */
        Operator: Operator,
        /**
         * The OperatorSetting model constructor.
         * @property {OperatorSetting}
         */
        OperatorSetting: OperatorSetting,
        /**
         * The Operators model constructor.
         * @property {Operators}
         */
        Operators: Operators,
        /**
         * The DataAnchoringTransactionApi service constructor.
         * @property {DataAnchoringTransactionApi}
         */
        DataAnchoringTransactionApi: DataAnchoringTransactionApi,
        /**
         * The OperatorApi service constructor.
         * @property {OperatorApi}
         */
        OperatorApi: OperatorApi,

        // TokenHistory
        /**
         * The FTSummary model constructor.
         * @property {FTSummary}
         */
        FTSummary: FTSummary,
        /**
         * The FtContract model constructor.
         * @property {FtContract}
         */
        FtContract: FtContract,
        /**
         * The FtContractDetail model constructor.
         * @property {FtContractDetail}
         */
        FtContractDetail: FtContractDetail,
        /**
         * The FtTransfer model constructor.
         * @property {FtTransfer}
         */
        FtTransfer: FtTransfer,
        /**
         * The KlayTransfer model constructor.
         * @property {KlayTransfer}
         */
        KlayTransfer: KlayTransfer,
        /**
         * The Mt model constructor.
         * @property {Mt}
         */
        Mt: Mt,
        /**
         * The MtContract model constructor.
         * @property {MtContract}
         */
        MtContract: MtContract,
        /**
         * The MtContractDetail model constructor.
         * @property {MtContractDetail}
         */
        MtContractDetail: MtContractDetail,
        /**
         * The MtToken model constructor.
         * @property {MtToken}
         */
        MtToken: MtToken,
        /**
         * The MtTransfer model constructor.
         * @property {MtTransfer}
         */
        MtTransfer: MtTransfer,
        /**
         * The Nft model constructor.
         * @property {Nft}
         */
        Nft: Nft,
        /**
         * The NftContract model constructor.
         * @property {NftContract}
         */
        NftContract: NftContract,
        /**
         * The NftContractDetail model constructor.
         * @property {NftContractDetail}
         */
        NftContractDetail: NftContractDetail,
        /**
         * The NftOwnershipChange model constructor.
         * @property {NftOwnershipChange}
         */
        NftOwnershipChange: NftOwnershipChange,
        /**
         * The NftTransfer model constructor.
         * @property {NftTransfer}
         */
        NftTransfer: NftTransfer,
        /**
         * The PageableAccountFT model constructor.
         * @property {PageableAccountFT}
         */
        PageableAccountFT: PageableAccountFT,
        /**
         * The PageableFtContractDetails model constructor.
         * @property {PageableFtContractDetails}
         */
        PageableFtContractDetails: PageableFtContractDetails,
        /**
         * The PageableMtContractDetails model constructor.
         * @property {PageableMtContractDetails}
         */
        PageableMtContractDetails: PageableMtContractDetails,
        /**
         * The PageableMtTokens model constructor.
         * @property {PageableMtTokens}
         */
        PageableMtTokens: PageableMtTokens,
        /**
         * The PageableMtTokensWithBalance model constructor.
         * @property {PageableMtTokensWithBalance}
         */
        PageableMtTokensWithBalance: PageableMtTokensWithBalance,
        /**
         * The PageableMts model constructor.
         * @property {PageableMts}
         */
        PageableMts: PageableMts,
        /**
         * The PageableNftContractDetails model constructor.
         * @property {PageableNftContractDetails}
         */
        PageableNftContractDetails: PageableNftContractDetails,
        /**
         * The PageableNftOwnershipChanges model constructor.
         * @property {PageableNftOwnershipChanges}
         */
        PageableNftOwnershipChanges: PageableNftOwnershipChanges,
        /**
         * The PageableNfts model constructor.
         * @property {PageableNfts}
         */
        PageableNfts: PageableNfts,
        /**
         * The PageableTransfers model constructor.
         * @property {PageableTransfers}
         */
        PageableTransfers: PageableTransfers,
        /**
         * The Transaction model constructor.
         * @property {Transaction}
         */
        Transaction: Transaction,
        /**
         * The TransferItem model constructor.
         * @property {TransferItem}
         */
        TransferItem: TransferItem,
        /**
         * The Transfers model constructor.
         * @property {Transfers}
         */
        Transfers: Transfers,
        /**
         * The TokenApi service constructor.
         * @property {TokenApi}
         */
        TokenApi: TokenApi,
        /**
         * The TokenContractApi service constructor.
         * @property {TokenContractApi}
         */
        TokenContractApi: TokenContractApi,
        /**
         * The TokenHistoryApi service constructor.
         * @property {TokenHistoryApi}
         */
        TokenHistoryApi: TokenHistoryApi,
        /**
         * The TokenOwnershipApi service constructor.
         * @property {TokenOwnershipApi}
         */
        TokenOwnershipApi: TokenOwnershipApi,

        // Wallet

        /**
         * The Account model constructor.
         * @property {Account}
         */
        Account: Account,
        /**
         * The AccountByPubkey model constructor.
         * @property {AccountByPubkey}
         */
        AccountByPubkey: AccountByPubkey,
        /**
         * The AccountCountByAccountID model constructor.
         * @property {AccountCountByAccountID}
         */
        AccountCountByAccountID: AccountCountByAccountID,
        /**
         * The AccountCountByKRN model constructor.
         * @property {AccountCountByKRN}
         */
        AccountCountByKRN: AccountCountByKRN,
        /**
         * The AccountRegistration model constructor.
         * @property {AccountRegistration}
         */
        AccountRegistration: AccountRegistration,
        /**
         * The AccountStatus model constructor.
         * @property {AccountStatus}
         */
        AccountStatus: AccountStatus,
        /**
         * The AccountSummary model constructor.
         * @property {AccountSummary}
         */
        AccountSummary: AccountSummary,
        /**
         * The AccountUpdateTransactionRequest model constructor.
         * @property {AccountUpdateTransactionRequest}
         */
        AccountUpdateTransactionRequest: AccountUpdateTransactionRequest,
        /**
         * The Accounts model constructor.
         * @property {Accounts}
         */
        Accounts: Accounts,
        /**
         * The AccountsByPubkey model constructor.
         * @property {AccountsByPubkey}
         */
        AccountsByPubkey: AccountsByPubkey,
        /**
         * The AnchorTransactionRequest model constructor.
         * @property {AnchorTransactionRequest}
         */
        AnchorTransactionRequest: AnchorTransactionRequest,
        /**
         * The CallArgument model constructor.
         * @property {CallArgument}
         */
        CallArgument: CallArgument,
        /**
         * The CancelTransactionRequest model constructor.
         * @property {CancelTransactionRequest}
         */
        CancelTransactionRequest: CancelTransactionRequest,
        /**
         * The ContractCallData model constructor.
         * @property {ContractCallData}
         */
        ContractCallData: ContractCallData,
        /**
         * The ContractCallRequest model constructor.
         * @property {ContractCallRequest}
         */
        ContractCallRequest: ContractCallRequest,
        /**
         * The ContractCallResponse model constructor.
         * @property {ContractCallResponse}
         */
        ContractCallResponse: ContractCallResponse,
        /**
         * The ContractDeployTransactionRequest model constructor.
         * @property {ContractDeployTransactionRequest}
         */
        ContractDeployTransactionRequest: ContractDeployTransactionRequest,
        /**
         * The ContractExecutionTransactionRequest model constructor.
         * @property {ContractExecutionTransactionRequest}
         */
        ContractExecutionTransactionRequest: ContractExecutionTransactionRequest,
        /**
         * The EmptyUpdateKeyType model constructor.
         * @property {EmptyUpdateKeyType}
         */
        EmptyUpdateKeyType: EmptyUpdateKeyType,
        /**
         * The ErrorResponse model constructor.
         * @property {ErrorResponse}
         */
        ErrorResponse: ErrorResponse,
        /**
         * The EventLog model constructor.
         * @property {EventLog}
         */
        EventLog: EventLog,
        /**
         * The FDAccountUpdateTransactionRequest model constructor.
         * @property {FDAccountUpdateTransactionRequest}
         */
        FDAccountUpdateTransactionRequest: FDAccountUpdateTransactionRequest,
        /**
         * The FDAnchorTransactionRequest model constructor.
         * @property {FDAnchorTransactionRequest}
         */
        FDAnchorTransactionRequest: FDAnchorTransactionRequest,
        /**
         * The FDCancelTransactionRequest model constructor.
         * @property {FDCancelTransactionRequest}
         */
        FDCancelTransactionRequest: FDCancelTransactionRequest,
        /**
         * The FDContractDeployTransactionRequest model constructor.
         * @property {FDContractDeployTransactionRequest}
         */
        FDContractDeployTransactionRequest: FDContractDeployTransactionRequest,
        /**
         * The FDContractExecutionTransactionRequest model constructor.
         * @property {FDContractExecutionTransactionRequest}
         */
        FDContractExecutionTransactionRequest: FDContractExecutionTransactionRequest,
        /**
         * The FDProcessRLPRequest model constructor.
         * @property {FDProcessRLPRequest}
         */
        FDProcessRLPRequest: FDProcessRLPRequest,
        /**
         * The FDTransactionResult model constructor.
         * @property {FDTransactionResult}
         */
        FDTransactionResult: FDTransactionResult,
        /**
         * The FDUserAccountUpdateTransactionRequest model constructor.
         * @property {FDUserAccountUpdateTransactionRequest}
         */
        FDUserAccountUpdateTransactionRequest: FDUserAccountUpdateTransactionRequest,
        /**
         * The FDUserAnchorTransactionRequest model constructor.
         * @property {FDUserAnchorTransactionRequest}
         */
        FDUserAnchorTransactionRequest: FDUserAnchorTransactionRequest,
        /**
         * The FDUserCancelTransactionRequest model constructor.
         * @property {FDUserCancelTransactionRequest}
         */
        FDUserCancelTransactionRequest: FDUserCancelTransactionRequest,
        /**
         * The FDUserContractDeployTransactionRequest model constructor.
         * @property {FDUserContractDeployTransactionRequest}
         */
        FDUserContractDeployTransactionRequest: FDUserContractDeployTransactionRequest,
        /**
         * The FDUserContractExecutionTransactionRequest model constructor.
         * @property {FDUserContractExecutionTransactionRequest}
         */
        FDUserContractExecutionTransactionRequest: FDUserContractExecutionTransactionRequest,
        /**
         * The FDUserProcessRLPRequest model constructor.
         * @property {FDUserProcessRLPRequest}
         */
        FDUserProcessRLPRequest: FDUserProcessRLPRequest,
        /**
         * The FDUserValueTransferTransactionRequest model constructor.
         * @property {FDUserValueTransferTransactionRequest}
         */
        FDUserValueTransferTransactionRequest: FDUserValueTransferTransactionRequest,
        /**
         * The FDValueTransferTransactionRequest model constructor.
         * @property {FDValueTransferTransactionRequest}
         */
        FDValueTransferTransactionRequest: FDValueTransferTransactionRequest,
        /**
         * The FeePayerSignaturesObj model constructor.
         * @property {FeePayerSignaturesObj}
         */
        FeePayerSignaturesObj: FeePayerSignaturesObj,
        /**
         * The Key model constructor.
         * @property {Key}
         */
        Key: Key,
        /**
         * The KeyCreationRequest model constructor.
         * @property {KeyCreationRequest}
         */
        KeyCreationRequest: KeyCreationRequest,
        /**
         * The KeyCreationResponse model constructor.
         * @property {KeyCreationResponse}
         */
        KeyCreationResponse: KeyCreationResponse,
        /**
         * The KeySignDataRequest model constructor.
         * @property {KeySignDataRequest}
         */
        KeySignDataRequest: KeySignDataRequest,
        /**
         * The KeySignDataResponse model constructor.
         * @property {KeySignDataResponse}
         */
        KeySignDataResponse: KeySignDataResponse,
        /**
         * The KeyStatus model constructor.
         * @property {KeyStatus}
         */
        KeyStatus: KeyStatus,
        /**
         * The LegacyTransactionRequest model constructor.
         * @property {LegacyTransactionRequest}
         */
        LegacyTransactionRequest: LegacyTransactionRequest,
        /**
         * The MultisigAccount model constructor.
         * @property {MultisigAccount}
         */
        MultisigAccount: MultisigAccount,
        /**
         * The MultisigAccountUpdateRequest model constructor.
         * @property {MultisigAccountUpdateRequest}
         */
        MultisigAccountUpdateRequest: MultisigAccountUpdateRequest,
        /**
         * The MultisigAddress model constructor.
         * @property {MultisigAddress}
         */
        MultisigAddress: MultisigAddress,
        /**
         * The MultisigKey model constructor.
         * @property {MultisigKey}
         */
        MultisigKey: MultisigKey,
        /**
         * The MultisigTransactionStatus model constructor.
         * @property {MultisigTransactionStatus}
         */
        MultisigTransactionStatus: MultisigTransactionStatus,
        /**
         * The MultisigTransactions model constructor.
         * @property {MultisigTransactions}
         */
        MultisigTransactions: MultisigTransactions,
        /**
         * The MultisigUpdateKey model constructor.
         * @property {MultisigUpdateKey}
         */
        MultisigUpdateKey: MultisigUpdateKey,
        /**
         * The MultisigUpdateKeyType model constructor.
         * @property {MultisigUpdateKeyType}
         */
        MultisigUpdateKeyType: MultisigUpdateKeyType,
        /**
         * The PendedTransaction model constructor.
         * @property {PendedTransaction}
         */
        PendedTransaction: PendedTransaction,
        /**
         * The ProcessRLPRequest model constructor.
         * @property {ProcessRLPRequest}
         */
        ProcessRLPRequest: ProcessRLPRequest,
        /**
         * The PubkeyUpdateKeyType model constructor.
         * @property {PubkeyUpdateKeyType}
         */
        PubkeyUpdateKeyType: PubkeyUpdateKeyType,
        /**
         * The RoleBasedUpdateKeyType model constructor.
         * @property {RoleBasedUpdateKeyType}
         */
        RoleBasedUpdateKeyType: RoleBasedUpdateKeyType,
        /**
         * The SignPendingTransactionBySigRequest model constructor.
         * @property {SignPendingTransactionBySigRequest}
         */
        SignPendingTransactionBySigRequest: SignPendingTransactionBySigRequest,
        /**
         * The Signature model constructor.
         * @property {Signature}
         */
        Signature: Signature,
        /**
         * The RegistrationStatusResponse model constructor.
         * @property {RegistrationStatusResponse}
         */
        RegistrationStatusResponse: RegistrationStatusResponse,
        /**
         * The TransactionReceipt model constructor.
         * @property {TransactionReceipt}
         */
        TransactionReceipt: TransactionReceipt,
        /**
         * The TransactionResult model constructor.
         * @property {TransactionResult}
         */
        TransactionResult: TransactionResult,
        /**
         * The TxData model constructor.
         * @property {TxData}
         */
        TxData: TxData,
        /**
         * The ValueTransferTransactionRequest model constructor.
         * @property {ValueTransferTransactionRequest}
         */
        ValueTransferTransactionRequest: ValueTransferTransactionRequest,
        /**
         * The AccountApi service constructor.
         * @property {AccountApi}
         */
        AccountApi: AccountApi,
        /**
         * The BasicTransactionApi service constructor.
         * @property {BasicTransactionApi}
         */
        BasicTransactionApi: BasicTransactionApi,
        /**
         * The FeeDelegatedTransactionPaidByKASApi service constructor.
         * @property {FeeDelegatedTransactionPaidByKASApi}
         */
        FeeDelegatedTransactionPaidByKASApi: FeeDelegatedTransactionPaidByKASApi,
        /**
         * The FeeDelegatedTransactionPaidByUserApi service constructor.
         * @property {FeeDelegatedTransactionPaidByUserApi}
         */
        FeeDelegatedTransactionPaidByUserApi: FeeDelegatedTransactionPaidByUserApi,
        /**
         * The FeepayerApi service constructor.
         * @property {FeepayerApi}
         */
        FeepayerApi: FeepayerApi,
        /**
         * The KeyApi service constructor.
         * @property {KeyApi}
         */
        KeyApi: KeyApi,
        /**
         * The MultisigTransactionManagementApi service constructor.
         * @property {MultisigTransactionManagementApi}
         */
        MultisigTransactionManagementApi: MultisigTransactionManagementApi,
        /**
         * The RegistrationApi service constructor.
         * @property {RegistrationApi}
         */
        RegistrationApi: RegistrationApi,
        /**
         * The StatisticsApi service constructor.
         * @property {StatisticsApi}
         */
        StatisticsApi: StatisticsApi,

        // KIP17
        /**
         * The ApproveAllKip17Request model constructor.
         * @property {ApproveAllKip17Request}
         */
        ApproveAllKip17Request: ApproveAllKip17Request,
        /**
         * The ApproveKip17TokenRequest model constructor.
         * @property {ApproveKip17TokenRequest}
         */
        ApproveKip17TokenRequest: ApproveKip17TokenRequest,
        /**
         * The BurnKip17TokenRequest model constructor.
         * @property {BurnKip17TokenRequest}
         */
        BurnKip17TokenRequest: BurnKip17TokenRequest,
        /**
         * The DeployKip17ContractRequest model constructor.
         * @property {DeployKip17ContractRequest}
         */
        DeployKip17ContractRequest: DeployKip17ContractRequest,
        /**
         * The GetKip17TokenHistoryResponse model constructor.
         * @property {GetKip17TokenHistoryResponse}
         */
        GetKip17TokenHistoryResponse: GetKip17TokenHistoryResponse,
        /**
         * The GetKip17TokenHistoryResponseItem model constructor.
         * @property {GetKip17TokenHistoryResponseItem}
         */
        GetKip17TokenHistoryResponseItem: GetKip17TokenHistoryResponseItem,
        /**
         * The GetKip17TokenResponse model constructor.
         * @property {GetKip17TokenResponse}
         */
        GetKip17TokenResponse: GetKip17TokenResponse,
        /**
         * The GetOwnerKip17TokensResponse model constructor.
         * @property {GetOwnerKip17TokensResponse}
         */
        GetOwnerKip17TokensResponse: GetOwnerKip17TokensResponse,
        /**
         * The GetOwnerKip17TokensResponseItem model constructor.
         * @property {GetOwnerKip17TokensResponseItem}
         */
        GetOwnerKip17TokensResponseItem: GetOwnerKip17TokensResponseItem,
        /**
         * The Kip17ContractInfoResponse model constructor.
         * @property {Kip17ContractInfoResponse}
         */
        Kip17ContractInfoResponse: Kip17ContractInfoResponse,
        /**
         * The Kip17ContractListResponse model constructor.
         * @property {Kip17ContractListResponse}
         */
        Kip17ContractListResponse: Kip17ContractListResponse,
        /**
         * The Kip17ContractListResponseItem model constructor.
         * @property {Kip17ContractListResponseItem}
         */
        Kip17ContractListResponseItem: Kip17ContractListResponseItem,
        /**
         * The Kip17TokenListResponse model constructor.
         * @property {Kip17TokenListResponse}
         */
        Kip17TokenListResponse: Kip17TokenListResponse,
        /**
         * The Kip17TransactionStatusResponse model constructor.
         * @property {Kip17TransactionStatusResponse}
         */
        Kip17TransactionStatusResponse: Kip17TransactionStatusResponse,
        /**
         * The MintKip17TokenRequest model constructor.
         * @property {MintKip17TokenRequest}
         */
        MintKip17TokenRequest: MintKip17TokenRequest,
        /**
         * The TransferKip17TokenRequest model constructor.
         * @property {TransferKip17TokenRequest}
         */
        TransferKip17TokenRequest: TransferKip17TokenRequest,
        /**
         * The KIP17Api service constructor.
         * @property {KIP17Api}
         */
        KIP17Api: KIP17Api,

        // KIP7
        /**
         * The ApproveKip7TokenRequest model constructor.
         * @property {ApproveKip7TokenRequest}
         */
        ApproveKip7TokenRequest: ApproveKip7TokenRequest,
        /**
         * The BurnFromKip7TokenRequest model constructor.
         * @property {BurnFromKip7TokenRequest}
         */
        BurnFromKip7TokenRequest: BurnFromKip7TokenRequest,
        /**
         * The BurnKip7TokenRequest model constructor.
         * @property {BurnKip7TokenRequest}
         */
        BurnKip7TokenRequest: BurnKip7TokenRequest,
        /**
         * The DeployKip7ContractRequest model constructor.
         * @property {DeployKip7ContractRequest}
         */
        DeployKip7ContractRequest: DeployKip7ContractRequest,
        /**
         * The Kip7ContractListResponse model constructor.
         * @property {Kip7ContractListResponse}
         */
        Kip7ContractListResponse: Kip7ContractListResponse,
        /**
         * The Kip7ContractListResponseItem model constructor.
         * @property {Kip7ContractListResponseItem}
         */
        Kip7ContractListResponseItem: Kip7ContractListResponseItem,
        /**
         * The Kip7ContractMetadataResponse model constructor.
         * @property {Kip7ContractMetadataResponse}
         */
        Kip7ContractMetadataResponse: Kip7ContractMetadataResponse,
        /**
         * The Kip7DeployerResponse model constructor.
         * @property {Kip7DeployerResponse}
         */
        Kip7DeployerResponse: Kip7DeployerResponse,
        /**
         * The Kip7TokenBalanceResponse model constructor.
         * @property {Kip7TokenBalanceResponse}
         */
        Kip7TokenBalanceResponse: Kip7TokenBalanceResponse,
        /**
         * The Kip7TransactionStatusResponse model constructor.
         * @property {Kip7TransactionStatusResponse}
         */
        Kip7TransactionStatusResponse: Kip7TransactionStatusResponse,
        /**
         * The MintKip7TokenRequest model constructor.
         * @property {MintKip7TokenRequest}
         */
        MintKip7TokenRequest: MintKip7TokenRequest,
        /**
         * The TransferKip7TokenFromRequest model constructor.
         * @property {TransferKip7TokenFromRequest}
         */
        TransferKip7TokenFromRequest: TransferKip7TokenFromRequest,
        /**
         * The TransferKip7TokenRequest model constructor.
         * @property {TransferKip7TokenRequest}
         */
        TransferKip7TokenRequest: TransferKip7TokenRequest,
        /**
         * The KIP7Api service constructor.
         * @property {KIP7Api}
         */
        KIP7Api: KIP7Api,
        /**
         * The KIP7DeployerApi service constructor.
         * @property {KIP7DeployerApi}
         */
        KIP7DeployerApi: KIP7DeployerApi,
    }

    return exports
})
