/*
 * Anchor API
 * # Introduction 이 문서는 KAS\\(Klaytn API Service\\)의 Anchor API를 소개하는 문서입니다. Anchor API는 서비스 체인 데이터의 신뢰성을 보장하기 위해 데이터 신뢰성을 증명할 수 있는 메타데이터를 Klaytn 메인 체인에 전송하는 기능을 제공합니다.  자세한 사용 예시는 [튜토리얼](링크)를 확인하십시오.    # Error Codes  ## 400: Bad Request   | Code | Messages |   | --- | --- |   | 1071010 | data don't exist 1072100 | same payload ID or payload was already anchored 1072101 | all configured accounts have insufficient funds |
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

;(function(root, factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['../../ApiClient', '../model/ErrorResponse', '../model/Operator', '../model/Operators'], factory)
    } else if (typeof module === 'object' && module.exports) {
        // CommonJS-like environments that support module.exports, like Node.
        module.exports = factory(
            require('../../ApiClient'),
            require('../model/ErrorResponse'),
            require('../model/Operator'),
            require('../model/Operators')
        )
    } else {
        // Browser globals (root is window)
        if (!root.AnchorApi) {
            root.AnchorApi = {}
        }
        root.AnchorApi.OperatorApi = factory(
            root.AnchorApi.ApiClient,
            root.AnchorApi.ErrorResponse,
            root.AnchorApi.Operator,
            root.AnchorApi.Operators
        )
    }
})(this, function(ApiClient, ErrorResponse, Operator, Operators) {
    /**
     * Operator service.
     * @module api/OperatorApi
     * @version 1.0
     */

    /**
     * Constructs a new OperatorApi.
     * @alias module:api/OperatorApi
     * @class
     * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
     * default to {@link module:ApiClient#instance} if unspecified.
     */
    const exports = function(apiClient) {
        this.apiClient = apiClient || ApiClient.instance

        /**
         * Callback function to receive the result of the getOperator operation.
         * @callback module:api/OperatorApi~getOperatorCallback
         * @param {String} error Error message, if any.
         * @param {module:model/Operator} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         * GetOperator
         * 해당 오퍼레이터 설정 및 오퍼레이터 계정 잔액을 조회합니다.
         * @param {String} xChainId Klaytn 체인 네트워크 ID (1001 or 8217)
         * @param {String} operatorId 오퍼레이터 계정 주소
         * @param {module:api/OperatorApi~getOperatorCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/Operator}
         */
        this.getOperator = function(xChainId, operatorId, callback) {
            const postBody = null

            // verify the required parameter 'xChainId' is set
            if (xChainId === undefined || xChainId === null) {
                throw new Error("Missing the required parameter 'xChainId' when calling getOperator")
            }

            // verify the required parameter 'operatorId' is set
            if (operatorId === undefined || operatorId === null) {
                throw new Error("Missing the required parameter 'operatorId' when calling getOperator")
            }

            const pathParams = {
                'operator-id': operatorId,
            }
            const queryParams = {}
            const collectionQueryParams = {}
            const headerParams = {
                'x-chain-id': xChainId,
            }
            const formParams = {}

            const authNames = ['auth']
            const contentTypes = ['application/json']
            const accepts = ['application/json']
            const returnType = Operator

            return this.apiClient.callApi(
                '/v1/operator/{operator-id}',
                'GET',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback
            )
        }

        /**
         * Callback function to receive the result of the retrieveOperators operation.
         * @callback module:api/OperatorApi~retrieveOperatorsCallback
         * @param {String} error Error message, if any.
         * @param {module:model/Operators} data The data returned by the service call.
         * @param {String} response The complete HTTP response.
         */

        /**
         * RetrieveOperators
         * 이미 생성된 오퍼레이터 목록 및 각 오퍼레이터 설정값을 조회합니다.
         * @param {String} xChainId Klaytn 체인 네트워크 ID (1001 or 8217)
         * @param {Object} opts Optional parameters
         * @param {Number} opts.size 검색할 계정의 최대 사이즈 (default to 100)
         * @param {String} opts.cursor 마지막으로 검색된 커서의 정보
         * @param {Number} opts.fromTimestamp 검색하고자 하는 처음 시간의 타임스탬프 (초단위)
         * @param {Number} opts.toTimestamp 검색하고자 하는 마지막 시간의 타임스탬프 (초단위)
         * @param {module:api/OperatorApi~retrieveOperatorsCallback} callback The callback function, accepting three arguments: error, data, response
         * data is of type: {@link module:model/Operators}
         */
        this.retrieveOperators = function(xChainId, opts, callback) {
            opts = opts || {}
            const postBody = null

            // verify the required parameter 'xChainId' is set
            if (xChainId === undefined || xChainId === null) {
                throw new Error("Missing the required parameter 'xChainId' when calling retrieveOperators")
            }

            const pathParams = {}
            const queryParams = {
                size: opts.size,
                cursor: opts.cursor,
                'from-timestamp': opts.fromTimestamp,
                'to-timestamp': opts.toTimestamp,
            }
            const collectionQueryParams = {}
            const headerParams = {
                'x-chain-id': xChainId,
            }
            const formParams = {}

            const authNames = ['auth']
            const contentTypes = ['application/json']
            const accepts = ['application/json']
            const returnType = Operators

            return this.apiClient.callApi(
                '/v1/operator',
                'GET',
                pathParams,
                queryParams,
                collectionQueryParams,
                headerParams,
                formParams,
                postBody,
                authNames,
                contentTypes,
                accepts,
                returnType,
                callback
            )
        }
    }

    return exports
})
