/**
 * Metadata API
 * # Introduction  The Metadata API helps BApp (Blockchain Application) developers to manage assets and metadata for their tokens.  Asset and metadata are used when you mint Klaytn's [KIP-17](https://kips.klaytn.com/KIPs/kip-17) Tokens (NFTs), [KIP-37](https://kips.klaytn.com/KIPs/kip-37) Tokens (MTs).  An asset refers to an image or a video file of an NFT or MT. When you mint an NFT or MT, you first have to upload the asset and include the returned asset URI in the metadata when minting the token. Metadata originally refers to \"data of data\". In the context of NFTs or MTs, it refers to the properties (name, description, image URL etc.) of the tokens. It is stored in JSON format.  Metadata API enables you to do the following actions: - upload assets - upload metadata - provide an externally accessible URI for the assets and metadata  # Error Code This section contains the errors that might occur when using Metadata API. KAS uses [HTTP status codes](https://developer.mozilla.org/en/docs/Web/HTTP/Status). Error code tables can be found [here](#tag/err-400).
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


 const ApiClient = require('../../ApiClient')

 /**
  * The UploadAssetRequest model module.
  * @class UploadAssetRequest
  * @version 1.0
  */
 class UploadAssetRequest {
     /**
      * Constructs a new <code>UploadAssetRequest</code>.
      * @alias UploadAssetRequest
      * @class
      * @param file {String} Addes a file with multipart/form-data. File number is limited to one, and file size is limited to 10MB. If the file size exceeds 10MB, you will get an invalid input error.
      */
 
     constructor(file) {
         this.file = file
     }
 
     /**
      * Constructs a <code>UploadAssetRequest</code> from a plain JavaScript object, optionally creating a new instance.
      * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
      * @param {Object} data The plain JavaScript object bearing properties of interest.
      * @param {UploadAssetRequest} obj Optional instance to populate.
      * @return {UploadAssetRequest} The populated <code>UploadAssetRequest</code> instance.
      * @memberof UploadAssetRequest
      */
     static constructFromObject(data, obj) {
         if (data) {
             obj = obj || new UploadAssetRequest()
 
             if (data.hasOwnProperty('file')) {
                 obj.file = ApiClient.convertToType(data.file, 'String')
             }
         }
         return obj
     }
 }
 
 /**
  * Addes a file with multipart/form-data. File number is limited to one, and file size is limited to 10MB. If the file size exceeds 10MB, you will get an invalid input error.
  * @type {String}
  * @memberof UploadAssetRequest
  */
 UploadAssetRequest.prototype.file = undefined
 
 module.exports = UploadAssetRequest
